project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"
  post-render:
    # - "rsync --recursive --prune-empty-dirs --copy-links --safe-links static/. _site/"
    - "cp -rn static/. _site/"

website:
  title: "garrick"
  site-url: https://www.garrickadenbuie.com
  twitter-card:
    creator: "@grrrck"
    site: "@grrrck"
    card-style: summary_large_image
  open-graph: true
  navbar:
    background: light
    right:
      - text: blog
        href: blog/index.qmd
      - text: projects
        href: project/index.qmd
      - text: talks
        href: talk/index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/gadenbuie
      - icon: mastodon
        href: https://fosstodon.org/grrrck

format:
  html:
    theme:
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css: styles.css
    highlight-style: atom-one
    code-block-bg: false

execute:
  freeze: auto

