project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"
  post-render:
    - "rsync --recursive --prune-empty-dirs --copy-links --safe-links static/. _site/"

website:
  title: "garrick"
  site-url: https://garrickadenbuie.com
  twitter-card:
    creator: "@grrrck"
    site: "@grrrck"
    card-style: summary_large_image
  open-graph: true
  navbar:
    right:
      - text: blog
        href: blog/index.qmd
      - text: projects
        href: project/index.qmd
      - text: talks
        href: talk/index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: zephyr
    css: styles.css

execute:
  freeze: auto

