project:
  type: website
  resources:
    - "static"
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"

website:
  title: "garrick"
  site-url: https://garrickadenbuie.com
  navbar:
    right:
      - text: blog
        href: blog/index.qmd
      - text: projects
        href: project/index.qmd
      - text: talks
        href: talk/index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

